replicaCount: 2

image:
  repository: ghcr.io/entropyrabbit/ravich.cloud
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  hosts: 
    - ravich.cloud
    - www.ravich.cloud

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"
